### ISSUE TITLE
Support ESP IDF v5.1

### ISSUE THREAD

**Issue by misterb0407** [edgeimpulse/example-standalone-inferencing-espressif-esp32#7]
Steps:
1. Integrate the generated C++ library from Edge Impulse studio (folder only)
2. Build with docker images ESP IDV v4.4 -> **Successful**
`docker run --rm -v $PWD:/project -w /project -it espressif/idf:release-v4.4 build`
3. Clean the build from 2)
`docker run --rm -v $PWD:/project -w /project -it espressif/idf:release-v4.4 full clean`
`rm -rf build`
4. Now build with ESP IDF v5.1 -> **Fail**
`docker run --rm -v $PWD:/project -w /project -it espressif/idf:release-v5.1 build`

Snippet of the build log error:
`/project/edge-impulse-sdk/porting/espressif/ei_classifier_porting.cpp: In function 'EI_IMPULSE_ERROR ei_sleep(int32_t)':
/project/edge-impulse-sdk/porting/espressif/ei_classifier_porting.cpp:39:26: error: 'portTICK_RATE_MS' was not declared in this scope; did you mean 'portTICK_PERIOD_MS'?
   39 |     vTaskDelay(time_ms / portTICK_RATE_MS);
      |                          ^~~~~~~~~~~~~~~~
      |                          portTICK_PERIOD_MS`

.... (bunch of ` [-Wmissing-field-initializers]` warnings) ...

`ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /project/build/log/idf_py_stderr_output_452 and /project/build/log/idf_py_stdout_output_452`

**Comment by AIWintermuteAI** [comment]
Hi!
See the requirement section in the README:
https://github.com/edgeimpulse/example-standalone-inferencing-espressif-esp32#software
It requires ESP IDF 4.4..

**Comment by misterb0407** [comment]
Hi @AIWintermuteAI ,
Thanks for the reply, what is Edge Impulse recommendation then for existing project that already in production but using other version than ESP IDFv4.4?

**Comment by AIWintermuteAI** [comment]
Either port the project to IDF 4.4 or have a look at what changes need to be done in edge-impulse-sdk/porting/espressif/ei_classifier_porting.cpp to accommodate IDF version that you are using. 
This is target specific porting layer, which defines some important functions for running inference.

**Comment by misterb0407** [comment]
Got it, thank you!

**Comment by matti122** [comment]
Hi @AIWintermuteAI ,
I'm also trying to port edge-impulse-sdk to ESP-IDF 5.1 without any success.
Are there any future Plans to support ESP-IDF 5.1?

**Comment by AIWintermuteAI** [comment]
Not at the moment, not. I'll put it on agenda though, but cannot give you a timeline. 
Where are you getting stuck with ESP-IDF 5.1 ?

**Comment by matti122** [comment]
Hi @AIWintermuteAI ,
I was able to fix some issues but now I'm getting a lot of  "undefined reference to" and "multiple defition" errors. This might be an error in relation with the Toolchain. But I'm not able to fix it.
Here are some examples:
/edge-impulse-sdk/classifier/ei_run_classifier.h:619: multiple definition of `run_classifier';
edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.cc:1306: undefined reference to `esp_nn_max_pool_s8_esp32s3'
edge-impulse-sdk/classifier/inferencing_engines/tflite_helper.h:277: multiple definition of `_Z44fill_result_struct_from_output_tensor_tflitePK10ei_impulseP12TfLiteTensorS3_S3_P19ei_impulse_result_tb';

**Comment by matti122** [comment]
Hi @AIWintermuteAI  ,
I was able to find a Repo with the missing CMake Configurations. https://github.com/klumw/keyword_detection
So my problem is solved.
